PROJECT_LEADERS = {
    "ALL": [],
    "Angel Marin": ["SUDLR", "SECCC", "SERPC", "DRRPC", "SECLR"],
    "Alain Chalut": ["DRMZT"],
    "Chad Knowles": ["ZOMSL", "SEWMB", "SMBSL", "SEAUA"],
    "Claudio Balderrama": ["SUDIX"],
    "Cristina Ortiz": ["DRBMI", "SEBMI"],
    "Florin Ignat": ["DRJRC", "SEMRC", "DRENA", "SEPDC", "BRERG", "BRERC", "DRERC", "CUNPC", "CUNIF", "DRSRC", "SECUN", "CANIA", "HVPDC"],
    "Gabriel Prado": ["SETPC", "DRMPC", "DRFPC", "BREPC", "DRCTG", "DRECC", "DROPC", "DREPE", "DRELR", "PUJIF", "DREPB", "DREPC", "DREDL"],
    "Guillermo Mejia": ["DDPBP", "DRCUR", "SEAUA", "ZOCUR"],
    "Kamar Tucker": ["SMBSL", "ZOMSL"],
    "Ivan Brambila": ["DRVPV", "SEVPV", "SUNPV"],
    "Juan Manuel Marquez": ["PVRIF"],
    "Ladislao Oquendo": ["SECHU", "DREHU"],
    "Ricardo Arriola": ["BRCSL", "DRELC", "SEPLC", "ZOCDM"],
    "Rodolfo Osoyo": ["SEARM", "DRETU", "DRCZM", "DREPA", "SEACZ", "SECTU"],
    "Victor Camarillo": ["DREPM", "SEPBC", "SEVCU", "NOECU", "DREVC", "BRECU", "CANIF", "SEIIM", "CUNIA", "HYVGI"],
}
